#!/bin/bash
This is the main Page, The assignment we are given is making a lot of sense, though its hard, but we are gradually getting a glimpse of what Software Engineering is all about, I hope to learn as much as much God helping me as an ALX Student.

